apiVersion: v1
kind: Service
metadata:
  name: blockchain-interaction-service
  labels:
    app: blockchain-interaction
spec:
  selector:
    app: blockchain-interaction
  ports:
    - name: grpc
      protocol: TCP
      port: 4001
      targetPort: 4001
  type: ClusterIP